// Proto contract for the kompetitor module's gRPC presentation layer.
// Messages mirror modules/kompetitor/application/dto/dto.go field-for-field;
// RPCs mirror the retired Laravel KompetitorController methods one-to-one.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: kompetitor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KompetitorService_IndexMeta_FullMethodName         = "/kompetitor.KompetitorService/IndexMeta"
	KompetitorService_ManageData_FullMethodName        = "/kompetitor.KompetitorService/ManageData"
	KompetitorService_CreateKompetitor_FullMethodName  = "/kompetitor.KompetitorService/CreateKompetitor"
	KompetitorService_UpdateKompetitor_FullMethodName  = "/kompetitor.KompetitorService/UpdateKompetitor"
	KompetitorService_DeleteKompetitor_FullMethodName  = "/kompetitor.KompetitorService/DeleteKompetitor"
	KompetitorService_MappingMatrix_FullMethodName     = "/kompetitor.KompetitorService/MappingMatrix"
	KompetitorService_MappingCell_FullMethodName       = "/kompetitor.KompetitorService/MappingCell"
	KompetitorService_MappingCellUpdate_FullMethodName = "/kompetitor.KompetitorService/MappingCellUpdate"
	KompetitorService_Stats_FullMethodName             = "/kompetitor.KompetitorService/Stats"
	KompetitorService_Products_FullMethodName          = "/kompetitor.KompetitorService/Products"
	KompetitorService_LegacyProducts_FullMethodName    = "/kompetitor.KompetitorService/LegacyProducts"
	KompetitorService_BatchCodes_FullMethodName        = "/kompetitor.KompetitorService/BatchCodes"
	KompetitorService_FilterOptions_FullMethodName     = "/kompetitor.KompetitorService/FilterOptions"
	KompetitorService_OurProducts_FullMethodName       = "/kompetitor.KompetitorService/OurProducts"
	KompetitorService_ImportProducts_FullMethodName    = "/kompetitor.KompetitorService/ImportProducts"
)

// KompetitorServiceClient is the client API for KompetitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KompetitorServiceClient interface {
	// ── Kompetitor CRUD (tab Kelola Kompetitor) ──────────────────────────
	IndexMeta(ctx context.Context, in *IndexMetaRequest, opts ...grpc.CallOption) (*IndexMetaResponse, error)
	ManageData(ctx context.Context, in *ManageDataRequest, opts ...grpc.CallOption) (*ManageDataResponse, error)
	CreateKompetitor(ctx context.Context, in *SaveKompetitorRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	UpdateKompetitor(ctx context.Context, in *SaveKompetitorRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	DeleteKompetitor(ctx context.Context, in *DeleteKompetitorRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// ── Mapping kompetitor (matrix kategori × brand) ─────────────────────
	MappingMatrix(ctx context.Context, in *MappingMatrixRequest, opts ...grpc.CallOption) (*MappingMatrixResponse, error)
	MappingCell(ctx context.Context, in *MappingCellRequest, opts ...grpc.CallOption) (*MappingCellResponse, error)
	MappingCellUpdate(ctx context.Context, in *MappingCellUpdateRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// ── Riset Produk (stats + product tables) ────────────────────────────
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	Products(ctx context.Context, in *ProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
	LegacyProducts(ctx context.Context, in *LegacyProductsRequest, opts ...grpc.CallOption) (*LegacyProductsResponse, error)
	BatchCodes(ctx context.Context, in *BatchCodesRequest, opts ...grpc.CallOption) (*BatchCodesResponse, error)
	// ── Our Product ──────────────────────────────────────────────────────
	FilterOptions(ctx context.Context, in *FilterOptionsRequest, opts ...grpc.CallOption) (*FilterOptionsResponse, error)
	OurProducts(ctx context.Context, in *OurProductsRequest, opts ...grpc.CallOption) (*OurProductsResponse, error)
	// ── Ingest (Laravel parses the Excel, sends plain rows) ──────────────
	ImportProducts(ctx context.Context, in *ImportProductsRequest, opts ...grpc.CallOption) (*ImportProductsResponse, error)
}

type kompetitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKompetitorServiceClient(cc grpc.ClientConnInterface) KompetitorServiceClient {
	return &kompetitorServiceClient{cc}
}

func (c *kompetitorServiceClient) IndexMeta(ctx context.Context, in *IndexMetaRequest, opts ...grpc.CallOption) (*IndexMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexMetaResponse)
	err := c.cc.Invoke(ctx, KompetitorService_IndexMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) ManageData(ctx context.Context, in *ManageDataRequest, opts ...grpc.CallOption) (*ManageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageDataResponse)
	err := c.cc.Invoke(ctx, KompetitorService_ManageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) CreateKompetitor(ctx context.Context, in *SaveKompetitorRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, KompetitorService_CreateKompetitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) UpdateKompetitor(ctx context.Context, in *SaveKompetitorRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, KompetitorService_UpdateKompetitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) DeleteKompetitor(ctx context.Context, in *DeleteKompetitorRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, KompetitorService_DeleteKompetitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) MappingMatrix(ctx context.Context, in *MappingMatrixRequest, opts ...grpc.CallOption) (*MappingMatrixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MappingMatrixResponse)
	err := c.cc.Invoke(ctx, KompetitorService_MappingMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) MappingCell(ctx context.Context, in *MappingCellRequest, opts ...grpc.CallOption) (*MappingCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MappingCellResponse)
	err := c.cc.Invoke(ctx, KompetitorService_MappingCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) MappingCellUpdate(ctx context.Context, in *MappingCellUpdateRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, KompetitorService_MappingCellUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, KompetitorService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) Products(ctx context.Context, in *ProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductsResponse)
	err := c.cc.Invoke(ctx, KompetitorService_Products_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) LegacyProducts(ctx context.Context, in *LegacyProductsRequest, opts ...grpc.CallOption) (*LegacyProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegacyProductsResponse)
	err := c.cc.Invoke(ctx, KompetitorService_LegacyProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) BatchCodes(ctx context.Context, in *BatchCodesRequest, opts ...grpc.CallOption) (*BatchCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCodesResponse)
	err := c.cc.Invoke(ctx, KompetitorService_BatchCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) FilterOptions(ctx context.Context, in *FilterOptionsRequest, opts ...grpc.CallOption) (*FilterOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterOptionsResponse)
	err := c.cc.Invoke(ctx, KompetitorService_FilterOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) OurProducts(ctx context.Context, in *OurProductsRequest, opts ...grpc.CallOption) (*OurProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OurProductsResponse)
	err := c.cc.Invoke(ctx, KompetitorService_OurProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kompetitorServiceClient) ImportProducts(ctx context.Context, in *ImportProductsRequest, opts ...grpc.CallOption) (*ImportProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportProductsResponse)
	err := c.cc.Invoke(ctx, KompetitorService_ImportProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KompetitorServiceServer is the server API for KompetitorService service.
// All implementations must embed UnimplementedKompetitorServiceServer
// for forward compatibility.
type KompetitorServiceServer interface {
	// ── Kompetitor CRUD (tab Kelola Kompetitor) ──────────────────────────
	IndexMeta(context.Context, *IndexMetaRequest) (*IndexMetaResponse, error)
	ManageData(context.Context, *ManageDataRequest) (*ManageDataResponse, error)
	CreateKompetitor(context.Context, *SaveKompetitorRequest) (*MessageResponse, error)
	UpdateKompetitor(context.Context, *SaveKompetitorRequest) (*MessageResponse, error)
	DeleteKompetitor(context.Context, *DeleteKompetitorRequest) (*MessageResponse, error)
	// ── Mapping kompetitor (matrix kategori × brand) ─────────────────────
	MappingMatrix(context.Context, *MappingMatrixRequest) (*MappingMatrixResponse, error)
	MappingCell(context.Context, *MappingCellRequest) (*MappingCellResponse, error)
	MappingCellUpdate(context.Context, *MappingCellUpdateRequest) (*MessageResponse, error)
	// ── Riset Produk (stats + product tables) ────────────────────────────
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	Products(context.Context, *ProductsRequest) (*ProductsResponse, error)
	LegacyProducts(context.Context, *LegacyProductsRequest) (*LegacyProductsResponse, error)
	BatchCodes(context.Context, *BatchCodesRequest) (*BatchCodesResponse, error)
	// ── Our Product ──────────────────────────────────────────────────────
	FilterOptions(context.Context, *FilterOptionsRequest) (*FilterOptionsResponse, error)
	OurProducts(context.Context, *OurProductsRequest) (*OurProductsResponse, error)
	// ── Ingest (Laravel parses the Excel, sends plain rows) ──────────────
	ImportProducts(context.Context, *ImportProductsRequest) (*ImportProductsResponse, error)
	mustEmbedUnimplementedKompetitorServiceServer()
}

// UnimplementedKompetitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKompetitorServiceServer struct{}

func (UnimplementedKompetitorServiceServer) IndexMeta(context.Context, *IndexMetaRequest) (*IndexMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexMeta not implemented")
}
func (UnimplementedKompetitorServiceServer) ManageData(context.Context, *ManageDataRequest) (*ManageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageData not implemented")
}
func (UnimplementedKompetitorServiceServer) CreateKompetitor(context.Context, *SaveKompetitorRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKompetitor not implemented")
}
func (UnimplementedKompetitorServiceServer) UpdateKompetitor(context.Context, *SaveKompetitorRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKompetitor not implemented")
}
func (UnimplementedKompetitorServiceServer) DeleteKompetitor(context.Context, *DeleteKompetitorRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKompetitor not implemented")
}
func (UnimplementedKompetitorServiceServer) MappingMatrix(context.Context, *MappingMatrixRequest) (*MappingMatrixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingMatrix not implemented")
}
func (UnimplementedKompetitorServiceServer) MappingCell(context.Context, *MappingCellRequest) (*MappingCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingCell not implemented")
}
func (UnimplementedKompetitorServiceServer) MappingCellUpdate(context.Context, *MappingCellUpdateRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingCellUpdate not implemented")
}
func (UnimplementedKompetitorServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedKompetitorServiceServer) Products(context.Context, *ProductsRequest) (*ProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Products not implemented")
}
func (UnimplementedKompetitorServiceServer) LegacyProducts(context.Context, *LegacyProductsRequest) (*LegacyProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LegacyProducts not implemented")
}
func (UnimplementedKompetitorServiceServer) BatchCodes(context.Context, *BatchCodesRequest) (*BatchCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCodes not implemented")
}
func (UnimplementedKompetitorServiceServer) FilterOptions(context.Context, *FilterOptionsRequest) (*FilterOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilterOptions not implemented")
}
func (UnimplementedKompetitorServiceServer) OurProducts(context.Context, *OurProductsRequest) (*OurProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OurProducts not implemented")
}
func (UnimplementedKompetitorServiceServer) ImportProducts(context.Context, *ImportProductsRequest) (*ImportProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportProducts not implemented")
}
func (UnimplementedKompetitorServiceServer) mustEmbedUnimplementedKompetitorServiceServer() {}
func (UnimplementedKompetitorServiceServer) testEmbeddedByValue()                           {}

// UnsafeKompetitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KompetitorServiceServer will
// result in compilation errors.
type UnsafeKompetitorServiceServer interface {
	mustEmbedUnimplementedKompetitorServiceServer()
}

func RegisterKompetitorServiceServer(s grpc.ServiceRegistrar, srv KompetitorServiceServer) {
	// If the following call panics, it indicates UnimplementedKompetitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KompetitorService_ServiceDesc, srv)
}

func _KompetitorService_IndexMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).IndexMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_IndexMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).IndexMeta(ctx, req.(*IndexMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_ManageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).ManageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_ManageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).ManageData(ctx, req.(*ManageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_CreateKompetitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveKompetitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).CreateKompetitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_CreateKompetitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).CreateKompetitor(ctx, req.(*SaveKompetitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_UpdateKompetitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveKompetitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).UpdateKompetitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_UpdateKompetitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).UpdateKompetitor(ctx, req.(*SaveKompetitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_DeleteKompetitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKompetitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).DeleteKompetitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_DeleteKompetitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).DeleteKompetitor(ctx, req.(*DeleteKompetitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_MappingMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).MappingMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_MappingMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).MappingMatrix(ctx, req.(*MappingMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_MappingCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).MappingCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_MappingCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).MappingCell(ctx, req.(*MappingCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_MappingCellUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingCellUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).MappingCellUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_MappingCellUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).MappingCellUpdate(ctx, req.(*MappingCellUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_Products_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).Products(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_Products_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).Products(ctx, req.(*ProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_LegacyProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegacyProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).LegacyProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_LegacyProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).LegacyProducts(ctx, req.(*LegacyProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_BatchCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).BatchCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_BatchCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).BatchCodes(ctx, req.(*BatchCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_FilterOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).FilterOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_FilterOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).FilterOptions(ctx, req.(*FilterOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_OurProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OurProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).OurProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_OurProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).OurProducts(ctx, req.(*OurProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KompetitorService_ImportProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KompetitorServiceServer).ImportProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KompetitorService_ImportProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KompetitorServiceServer).ImportProducts(ctx, req.(*ImportProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KompetitorService_ServiceDesc is the grpc.ServiceDesc for KompetitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KompetitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kompetitor.KompetitorService",
	HandlerType: (*KompetitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexMeta",
			Handler:    _KompetitorService_IndexMeta_Handler,
		},
		{
			MethodName: "ManageData",
			Handler:    _KompetitorService_ManageData_Handler,
		},
		{
			MethodName: "CreateKompetitor",
			Handler:    _KompetitorService_CreateKompetitor_Handler,
		},
		{
			MethodName: "UpdateKompetitor",
			Handler:    _KompetitorService_UpdateKompetitor_Handler,
		},
		{
			MethodName: "DeleteKompetitor",
			Handler:    _KompetitorService_DeleteKompetitor_Handler,
		},
		{
			MethodName: "MappingMatrix",
			Handler:    _KompetitorService_MappingMatrix_Handler,
		},
		{
			MethodName: "MappingCell",
			Handler:    _KompetitorService_MappingCell_Handler,
		},
		{
			MethodName: "MappingCellUpdate",
			Handler:    _KompetitorService_MappingCellUpdate_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _KompetitorService_Stats_Handler,
		},
		{
			MethodName: "Products",
			Handler:    _KompetitorService_Products_Handler,
		},
		{
			MethodName: "LegacyProducts",
			Handler:    _KompetitorService_LegacyProducts_Handler,
		},
		{
			MethodName: "BatchCodes",
			Handler:    _KompetitorService_BatchCodes_Handler,
		},
		{
			MethodName: "FilterOptions",
			Handler:    _KompetitorService_FilterOptions_Handler,
		},
		{
			MethodName: "OurProducts",
			Handler:    _KompetitorService_OurProducts_Handler,
		},
		{
			MethodName: "ImportProducts",
			Handler:    _KompetitorService_ImportProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kompetitor.proto",
}
