// Proto contract for the kompetitor module's gRPC presentation layer.
// Messages mirror modules/kompetitor/application/dto/dto.go field-for-field;
// RPCs mirror the retired Laravel KompetitorController methods one-to-one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: kompetitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NamedRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedRow) Reset() {
	*x = NamedRow{}
	mi := &file_kompetitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedRow) ProtoMessage() {}

func (x *NamedRow) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedRow.ProtoReflect.Descriptor instead.
func (*NamedRow) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{0}
}

func (x *NamedRow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NamedRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_kompetitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IndexMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMetaRequest) Reset() {
	*x = IndexMetaRequest{}
	mi := &file_kompetitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMetaRequest) ProtoMessage() {}

func (x *IndexMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMetaRequest.ProtoReflect.Descriptor instead.
func (*IndexMetaRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{2}
}

type KompetitorMetaRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MustScrape    bool                   `protobuf:"varint,3,opt,name=must_scrape,json=mustScrape,proto3" json:"must_scrape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KompetitorMetaRow) Reset() {
	*x = KompetitorMetaRow{}
	mi := &file_kompetitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KompetitorMetaRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KompetitorMetaRow) ProtoMessage() {}

func (x *KompetitorMetaRow) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KompetitorMetaRow.ProtoReflect.Descriptor instead.
func (*KompetitorMetaRow) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{3}
}

func (x *KompetitorMetaRow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KompetitorMetaRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KompetitorMetaRow) GetMustScrape() bool {
	if x != nil {
		return x.MustScrape
	}
	return false
}

type IndexMetaResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ListKompetitor     []*NamedRow            `protobuf:"bytes,1,rep,name=list_kompetitor,json=listKompetitor,proto3" json:"list_kompetitor,omitempty"`
	ListAllKompetitor  []*KompetitorMetaRow   `protobuf:"bytes,2,rep,name=list_all_kompetitor,json=listAllKompetitor,proto3" json:"list_all_kompetitor,omitempty"`
	DbklikKompetitorId uint64                 `protobuf:"varint,3,opt,name=dbklik_kompetitor_id,json=dbklikKompetitorId,proto3" json:"dbklik_kompetitor_id,omitempty"`
	ListBrand          []*NamedRow            `protobuf:"bytes,4,rep,name=list_brand,json=listBrand,proto3" json:"list_brand,omitempty"`
	ListKategori       []*NamedRow            `protobuf:"bytes,5,rep,name=list_kategori,json=listKategori,proto3" json:"list_kategori,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IndexMetaResponse) Reset() {
	*x = IndexMetaResponse{}
	mi := &file_kompetitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMetaResponse) ProtoMessage() {}

func (x *IndexMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMetaResponse.ProtoReflect.Descriptor instead.
func (*IndexMetaResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{4}
}

func (x *IndexMetaResponse) GetListKompetitor() []*NamedRow {
	if x != nil {
		return x.ListKompetitor
	}
	return nil
}

func (x *IndexMetaResponse) GetListAllKompetitor() []*KompetitorMetaRow {
	if x != nil {
		return x.ListAllKompetitor
	}
	return nil
}

func (x *IndexMetaResponse) GetDbklikKompetitorId() uint64 {
	if x != nil {
		return x.DbklikKompetitorId
	}
	return 0
}

func (x *IndexMetaResponse) GetListBrand() []*NamedRow {
	if x != nil {
		return x.ListBrand
	}
	return nil
}

func (x *IndexMetaResponse) GetListKategori() []*NamedRow {
	if x != nil {
		return x.ListKategori
	}
	return nil
}

type ManageDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageDataRequest) Reset() {
	*x = ManageDataRequest{}
	mi := &file_kompetitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageDataRequest) ProtoMessage() {}

func (x *ManageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageDataRequest.ProtoReflect.Descriptor instead.
func (*ManageDataRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{5}
}

type KompetitorRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShopeeCode    string                 `protobuf:"bytes,3,opt,name=shopee_code,json=shopeeCode,proto3" json:"shopee_code,omitempty"`
	TokopediaCode string                 `protobuf:"bytes,4,opt,name=tokopedia_code,json=tokopediaCode,proto3" json:"tokopedia_code,omitempty"`
	MustScrape    bool                   `protobuf:"varint,5,opt,name=must_scrape,json=mustScrape,proto3" json:"must_scrape,omitempty"`
	MappingCount  int64                  `protobuf:"varint,6,opt,name=mapping_count,json=mappingCount,proto3" json:"mapping_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KompetitorRow) Reset() {
	*x = KompetitorRow{}
	mi := &file_kompetitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KompetitorRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KompetitorRow) ProtoMessage() {}

func (x *KompetitorRow) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KompetitorRow.ProtoReflect.Descriptor instead.
func (*KompetitorRow) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{6}
}

func (x *KompetitorRow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KompetitorRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KompetitorRow) GetShopeeCode() string {
	if x != nil {
		return x.ShopeeCode
	}
	return ""
}

func (x *KompetitorRow) GetTokopediaCode() string {
	if x != nil {
		return x.TokopediaCode
	}
	return ""
}

func (x *KompetitorRow) GetMustScrape() bool {
	if x != nil {
		return x.MustScrape
	}
	return false
}

func (x *KompetitorRow) GetMappingCount() int64 {
	if x != nil {
		return x.MappingCount
	}
	return 0
}

type ManageDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*KompetitorRow       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageDataResponse) Reset() {
	*x = ManageDataResponse{}
	mi := &file_kompetitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageDataResponse) ProtoMessage() {}

func (x *ManageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageDataResponse.ProtoReflect.Descriptor instead.
func (*ManageDataResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{7}
}

func (x *ManageDataResponse) GetData() []*KompetitorRow {
	if x != nil {
		return x.Data
	}
	return nil
}

// SaveKompetitorRequest drives both create (id = 0) and update.
type SaveKompetitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShopeeCode    string                 `protobuf:"bytes,3,opt,name=shopee_code,json=shopeeCode,proto3" json:"shopee_code,omitempty"`
	TokopediaCode string                 `protobuf:"bytes,4,opt,name=tokopedia_code,json=tokopediaCode,proto3" json:"tokopedia_code,omitempty"`
	MustScrape    bool                   `protobuf:"varint,5,opt,name=must_scrape,json=mustScrape,proto3" json:"must_scrape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveKompetitorRequest) Reset() {
	*x = SaveKompetitorRequest{}
	mi := &file_kompetitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveKompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveKompetitorRequest) ProtoMessage() {}

func (x *SaveKompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveKompetitorRequest.ProtoReflect.Descriptor instead.
func (*SaveKompetitorRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{8}
}

func (x *SaveKompetitorRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveKompetitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveKompetitorRequest) GetShopeeCode() string {
	if x != nil {
		return x.ShopeeCode
	}
	return ""
}

func (x *SaveKompetitorRequest) GetTokopediaCode() string {
	if x != nil {
		return x.TokopediaCode
	}
	return ""
}

func (x *SaveKompetitorRequest) GetMustScrape() bool {
	if x != nil {
		return x.MustScrape
	}
	return false
}

type DeleteKompetitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKompetitorRequest) Reset() {
	*x = DeleteKompetitorRequest{}
	mi := &file_kompetitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKompetitorRequest) ProtoMessage() {}

func (x *DeleteKompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKompetitorRequest.ProtoReflect.Descriptor instead.
func (*DeleteKompetitorRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteKompetitorRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MappingMatrixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []uint64               `protobuf:"varint,1,rep,packed,name=brands,proto3" json:"brands,omitempty"`
	Kategoris     []uint64               `protobuf:"varint,2,rep,packed,name=kategoris,proto3" json:"kategoris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingMatrixRequest) Reset() {
	*x = MappingMatrixRequest{}
	mi := &file_kompetitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingMatrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingMatrixRequest) ProtoMessage() {}

func (x *MappingMatrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingMatrixRequest.ProtoReflect.Descriptor instead.
func (*MappingMatrixRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{10}
}

func (x *MappingMatrixRequest) GetBrands() []uint64 {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *MappingMatrixRequest) GetKategoris() []uint64 {
	if x != nil {
		return x.Kategoris
	}
	return nil
}

type MappingMatrixResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Brands    []*NamedRow            `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	Kategoris []*NamedRow            `protobuf:"bytes,2,rep,name=kategoris,proto3" json:"kategoris,omitempty"`
	// counts is keyed "kategoriID|brandID" (specific cells only).
	Counts map[string]int64 `protobuf:"bytes,3,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// universal_counts is keyed by brand id (kategori_id NULL cells).
	UniversalCounts map[uint64]int64 `protobuf:"bytes,4,rep,name=universal_counts,json=universalCounts,proto3" json:"universal_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Filtered        bool             `protobuf:"varint,5,opt,name=filtered,proto3" json:"filtered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MappingMatrixResponse) Reset() {
	*x = MappingMatrixResponse{}
	mi := &file_kompetitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingMatrixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingMatrixResponse) ProtoMessage() {}

func (x *MappingMatrixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingMatrixResponse.ProtoReflect.Descriptor instead.
func (*MappingMatrixResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{11}
}

func (x *MappingMatrixResponse) GetBrands() []*NamedRow {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *MappingMatrixResponse) GetKategoris() []*NamedRow {
	if x != nil {
		return x.Kategoris
	}
	return nil
}

func (x *MappingMatrixResponse) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *MappingMatrixResponse) GetUniversalCounts() map[uint64]int64 {
	if x != nil {
		return x.UniversalCounts
	}
	return nil
}

func (x *MappingMatrixResponse) GetFiltered() bool {
	if x != nil {
		return x.Filtered
	}
	return false
}

// An unset kategori_id addresses the brand's universal cell.
type MappingCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KategoriId    *uint64                `protobuf:"varint,1,opt,name=kategori_id,json=kategoriId,proto3,oneof" json:"kategori_id,omitempty"`
	BrandId       uint64                 `protobuf:"varint,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingCellRequest) Reset() {
	*x = MappingCellRequest{}
	mi := &file_kompetitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingCellRequest) ProtoMessage() {}

func (x *MappingCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingCellRequest.ProtoReflect.Descriptor instead.
func (*MappingCellRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{12}
}

func (x *MappingCellRequest) GetKategoriId() uint64 {
	if x != nil && x.KategoriId != nil {
		return *x.KategoriId
	}
	return 0
}

func (x *MappingCellRequest) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

type MappingCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KompetitorIds []uint64               `protobuf:"varint,1,rep,packed,name=kompetitor_ids,json=kompetitorIds,proto3" json:"kompetitor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingCellResponse) Reset() {
	*x = MappingCellResponse{}
	mi := &file_kompetitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingCellResponse) ProtoMessage() {}

func (x *MappingCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingCellResponse.ProtoReflect.Descriptor instead.
func (*MappingCellResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{13}
}

func (x *MappingCellResponse) GetKompetitorIds() []uint64 {
	if x != nil {
		return x.KompetitorIds
	}
	return nil
}

type MappingCellUpdateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	KategoriId *uint64                `protobuf:"varint,1,opt,name=kategori_id,json=kategoriId,proto3,oneof" json:"kategori_id,omitempty"`
	BrandId    uint64                 `protobuf:"varint,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	// An empty list deletes the cell.
	Kompetitors   []uint64 `protobuf:"varint,3,rep,packed,name=kompetitors,proto3" json:"kompetitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingCellUpdateRequest) Reset() {
	*x = MappingCellUpdateRequest{}
	mi := &file_kompetitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingCellUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingCellUpdateRequest) ProtoMessage() {}

func (x *MappingCellUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingCellUpdateRequest.ProtoReflect.Descriptor instead.
func (*MappingCellUpdateRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{14}
}

func (x *MappingCellUpdateRequest) GetKategoriId() uint64 {
	if x != nil && x.KategoriId != nil {
		return *x.KategoriId
	}
	return 0
}

func (x *MappingCellUpdateRequest) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *MappingCellUpdateRequest) GetKompetitors() []uint64 {
	if x != nil {
		return x.Kompetitors
	}
	return nil
}

// Both dates empty means "latest data"; kompetitor_id 0 means every store.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	KompetitorId  uint64                 `protobuf:"varint,3,opt,name=kompetitor_id,json=kompetitorId,proto3" json:"kompetitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_kompetitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{15}
}

func (x *StatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *StatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *StatsRequest) GetKompetitorId() uint64 {
	if x != nil {
		return x.KompetitorId
	}
	return 0
}

type StatsMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalOmzet        float64                `protobuf:"fixed64,1,opt,name=total_omzet,json=totalOmzet,proto3" json:"total_omzet,omitempty"`
	RataOmzetMinggu   float64                `protobuf:"fixed64,2,opt,name=rata_omzet_minggu,json=rataOmzetMinggu,proto3" json:"rata_omzet_minggu,omitempty"`
	RataOmzetHari     float64                `protobuf:"fixed64,3,opt,name=rata_omzet_hari,json=rataOmzetHari,proto3" json:"rata_omzet_hari,omitempty"`
	TotalTerjual      int64                  `protobuf:"varint,4,opt,name=total_terjual,json=totalTerjual,proto3" json:"total_terjual,omitempty"`
	RataTerjualMinggu float64                `protobuf:"fixed64,5,opt,name=rata_terjual_minggu,json=rataTerjualMinggu,proto3" json:"rata_terjual_minggu,omitempty"`
	RataTerjualHari   float64                `protobuf:"fixed64,6,opt,name=rata_terjual_hari,json=rataTerjualHari,proto3" json:"rata_terjual_hari,omitempty"`
	RataHarga         int64                  `protobuf:"varint,7,opt,name=rata_harga,json=rataHarga,proto3" json:"rata_harga,omitempty"`
	ProdukReady       int64                  `protobuf:"varint,8,opt,name=produk_ready,json=produkReady,proto3" json:"produk_ready,omitempty"`
	ProdukHabis       int64                  `protobuf:"varint,9,opt,name=produk_habis,json=produkHabis,proto3" json:"produk_habis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsMetrics) Reset() {
	*x = StatsMetrics{}
	mi := &file_kompetitor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsMetrics) ProtoMessage() {}

func (x *StatsMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsMetrics.ProtoReflect.Descriptor instead.
func (*StatsMetrics) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{16}
}

func (x *StatsMetrics) GetTotalOmzet() float64 {
	if x != nil {
		return x.TotalOmzet
	}
	return 0
}

func (x *StatsMetrics) GetRataOmzetMinggu() float64 {
	if x != nil {
		return x.RataOmzetMinggu
	}
	return 0
}

func (x *StatsMetrics) GetRataOmzetHari() float64 {
	if x != nil {
		return x.RataOmzetHari
	}
	return 0
}

func (x *StatsMetrics) GetTotalTerjual() int64 {
	if x != nil {
		return x.TotalTerjual
	}
	return 0
}

func (x *StatsMetrics) GetRataTerjualMinggu() float64 {
	if x != nil {
		return x.RataTerjualMinggu
	}
	return 0
}

func (x *StatsMetrics) GetRataTerjualHari() float64 {
	if x != nil {
		return x.RataTerjualHari
	}
	return 0
}

func (x *StatsMetrics) GetRataHarga() int64 {
	if x != nil {
		return x.RataHarga
	}
	return 0
}

func (x *StatsMetrics) GetProdukReady() int64 {
	if x != nil {
		return x.ProdukReady
	}
	return 0
}

func (x *StatsMetrics) GetProdukHabis() int64 {
	if x != nil {
		return x.ProdukHabis
	}
	return 0
}

// An absent current/previous block means "no data in that period" — the
// panel renders an empty state rather than zeroes.
type StatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Current         *StatsMetrics          `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Previous        *StatsMetrics          `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	CurrentBatches  []uint64               `protobuf:"varint,3,rep,packed,name=current_batches,json=currentBatches,proto3" json:"current_batches,omitempty"`
	PreviousBatches []uint64               `protobuf:"varint,4,rep,packed,name=previous_batches,json=previousBatches,proto3" json:"previous_batches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_kompetitor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{17}
}

func (x *StatsResponse) GetCurrent() *StatsMetrics {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *StatsResponse) GetPrevious() *StatsMetrics {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *StatsResponse) GetCurrentBatches() []uint64 {
	if x != nil {
		return x.CurrentBatches
	}
	return nil
}

func (x *StatsResponse) GetPreviousBatches() []uint64 {
	if x != nil {
		return x.PreviousBatches
	}
	return nil
}

type ProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	KompetitorId  uint64                 `protobuf:"varint,3,opt,name=kompetitor_id,json=kompetitorId,proto3" json:"kompetitor_id,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Start         int32                  `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Length        int32                  `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	Draw          int32                  `protobuf:"varint,7,opt,name=draw,proto3" json:"draw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsRequest) Reset() {
	*x = ProductsRequest{}
	mi := &file_kompetitor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsRequest) ProtoMessage() {}

func (x *ProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsRequest.ProtoReflect.Descriptor instead.
func (*ProductsRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{18}
}

func (x *ProductsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ProductsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ProductsRequest) GetKompetitorId() uint64 {
	if x != nil {
		return x.KompetitorId
	}
	return 0
}

func (x *ProductsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ProductsRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ProductsRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ProductsRequest) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

type ProductRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kompetitor      string                 `protobuf:"bytes,1,opt,name=kompetitor,proto3" json:"kompetitor,omitempty"`
	NamaProduk      string                 `protobuf:"bytes,2,opt,name=nama_produk,json=namaProduk,proto3" json:"nama_produk,omitempty"`
	Harga           string                 `protobuf:"bytes,3,opt,name=harga,proto3" json:"harga,omitempty"`
	PerubahanHarga  *float64               `protobuf:"fixed64,4,opt,name=perubahan_harga,json=perubahanHarga,proto3,oneof" json:"perubahan_harga,omitempty"`
	TerjualPerBulan int64                  `protobuf:"varint,5,opt,name=terjual_per_bulan,json=terjualPerBulan,proto3" json:"terjual_per_bulan,omitempty"`
	Pendapatan      string                 `protobuf:"bytes,6,opt,name=pendapatan,proto3" json:"pendapatan,omitempty"`
	RataHari        string                 `protobuf:"bytes,7,opt,name=rata_hari,json=rataHari,proto3" json:"rata_hari,omitempty"`
	Rating          *float64               `protobuf:"fixed64,8,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Stok            *int64                 `protobuf:"varint,9,opt,name=stok,proto3,oneof" json:"stok,omitempty"`
	BatchId         string                 `protobuf:"bytes,10,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductRow) Reset() {
	*x = ProductRow{}
	mi := &file_kompetitor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRow) ProtoMessage() {}

func (x *ProductRow) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRow.ProtoReflect.Descriptor instead.
func (*ProductRow) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{19}
}

func (x *ProductRow) GetKompetitor() string {
	if x != nil {
		return x.Kompetitor
	}
	return ""
}

func (x *ProductRow) GetNamaProduk() string {
	if x != nil {
		return x.NamaProduk
	}
	return ""
}

func (x *ProductRow) GetHarga() string {
	if x != nil {
		return x.Harga
	}
	return ""
}

func (x *ProductRow) GetPerubahanHarga() float64 {
	if x != nil && x.PerubahanHarga != nil {
		return *x.PerubahanHarga
	}
	return 0
}

func (x *ProductRow) GetTerjualPerBulan() int64 {
	if x != nil {
		return x.TerjualPerBulan
	}
	return 0
}

func (x *ProductRow) GetPendapatan() string {
	if x != nil {
		return x.Pendapatan
	}
	return ""
}

func (x *ProductRow) GetRataHari() string {
	if x != nil {
		return x.RataHari
	}
	return ""
}

func (x *ProductRow) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *ProductRow) GetStok() int64 {
	if x != nil && x.Stok != nil {
		return *x.Stok
	}
	return 0
}

func (x *ProductRow) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type ProductsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Draw            int32                  `protobuf:"varint,1,opt,name=draw,proto3" json:"draw,omitempty"`
	RecordsTotal    int64                  `protobuf:"varint,2,opt,name=records_total,json=recordsTotal,proto3" json:"records_total,omitempty"`
	RecordsFiltered int64                  `protobuf:"varint,3,opt,name=records_filtered,json=recordsFiltered,proto3" json:"records_filtered,omitempty"`
	Data            []*ProductRow          `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductsResponse) Reset() {
	*x = ProductsResponse{}
	mi := &file_kompetitor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsResponse) ProtoMessage() {}

func (x *ProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsResponse.ProtoReflect.Descriptor instead.
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{20}
}

func (x *ProductsResponse) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

func (x *ProductsResponse) GetRecordsTotal() int64 {
	if x != nil {
		return x.RecordsTotal
	}
	return 0
}

func (x *ProductsResponse) GetRecordsFiltered() int64 {
	if x != nil {
		return x.RecordsFiltered
	}
	return 0
}

func (x *ProductsResponse) GetData() []*ProductRow {
	if x != nil {
		return x.Data
	}
	return nil
}

type LegacyProductsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Search string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// kompetitor is a store NAME and batch a batch CODE, not ids.
	Kompetitor    string `protobuf:"bytes,2,opt,name=kompetitor,proto3" json:"kompetitor,omitempty"`
	Batch         string `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	Start         int32  `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	Length        int32  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	Draw          int32  `protobuf:"varint,6,opt,name=draw,proto3" json:"draw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacyProductsRequest) Reset() {
	*x = LegacyProductsRequest{}
	mi := &file_kompetitor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyProductsRequest) ProtoMessage() {}

func (x *LegacyProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyProductsRequest.ProtoReflect.Descriptor instead.
func (*LegacyProductsRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{21}
}

func (x *LegacyProductsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *LegacyProductsRequest) GetKompetitor() string {
	if x != nil {
		return x.Kompetitor
	}
	return ""
}

func (x *LegacyProductsRequest) GetBatch() string {
	if x != nil {
		return x.Batch
	}
	return ""
}

func (x *LegacyProductsRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LegacyProductsRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *LegacyProductsRequest) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

type LegacyProductRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kompetitor      string                 `protobuf:"bytes,1,opt,name=kompetitor,proto3" json:"kompetitor,omitempty"`
	NamaProduk      string                 `protobuf:"bytes,2,opt,name=nama_produk,json=namaProduk,proto3" json:"nama_produk,omitempty"`
	Harga           string                 `protobuf:"bytes,3,opt,name=harga,proto3" json:"harga,omitempty"`
	HargaRaw        float64                `protobuf:"fixed64,4,opt,name=harga_raw,json=hargaRaw,proto3" json:"harga_raw,omitempty"`
	TerjualPerBulan int64                  `protobuf:"varint,5,opt,name=terjual_per_bulan,json=terjualPerBulan,proto3" json:"terjual_per_bulan,omitempty"`
	Pendapatan      string                 `protobuf:"bytes,6,opt,name=pendapatan,proto3" json:"pendapatan,omitempty"`
	RataHari        string                 `protobuf:"bytes,7,opt,name=rata_hari,json=rataHari,proto3" json:"rata_hari,omitempty"`
	Rating          *float64               `protobuf:"fixed64,8,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	BatchId         string                 `protobuf:"bytes,9,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LegacyProductRow) Reset() {
	*x = LegacyProductRow{}
	mi := &file_kompetitor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyProductRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyProductRow) ProtoMessage() {}

func (x *LegacyProductRow) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyProductRow.ProtoReflect.Descriptor instead.
func (*LegacyProductRow) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{22}
}

func (x *LegacyProductRow) GetKompetitor() string {
	if x != nil {
		return x.Kompetitor
	}
	return ""
}

func (x *LegacyProductRow) GetNamaProduk() string {
	if x != nil {
		return x.NamaProduk
	}
	return ""
}

func (x *LegacyProductRow) GetHarga() string {
	if x != nil {
		return x.Harga
	}
	return ""
}

func (x *LegacyProductRow) GetHargaRaw() float64 {
	if x != nil {
		return x.HargaRaw
	}
	return 0
}

func (x *LegacyProductRow) GetTerjualPerBulan() int64 {
	if x != nil {
		return x.TerjualPerBulan
	}
	return 0
}

func (x *LegacyProductRow) GetPendapatan() string {
	if x != nil {
		return x.Pendapatan
	}
	return ""
}

func (x *LegacyProductRow) GetRataHari() string {
	if x != nil {
		return x.RataHari
	}
	return ""
}

func (x *LegacyProductRow) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *LegacyProductRow) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type LegacyProductsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Draw            int32                  `protobuf:"varint,1,opt,name=draw,proto3" json:"draw,omitempty"`
	RecordsTotal    int64                  `protobuf:"varint,2,opt,name=records_total,json=recordsTotal,proto3" json:"records_total,omitempty"`
	RecordsFiltered int64                  `protobuf:"varint,3,opt,name=records_filtered,json=recordsFiltered,proto3" json:"records_filtered,omitempty"`
	Data            []*LegacyProductRow    `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LegacyProductsResponse) Reset() {
	*x = LegacyProductsResponse{}
	mi := &file_kompetitor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyProductsResponse) ProtoMessage() {}

func (x *LegacyProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyProductsResponse.ProtoReflect.Descriptor instead.
func (*LegacyProductsResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{23}
}

func (x *LegacyProductsResponse) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

func (x *LegacyProductsResponse) GetRecordsTotal() int64 {
	if x != nil {
		return x.RecordsTotal
	}
	return 0
}

func (x *LegacyProductsResponse) GetRecordsFiltered() int64 {
	if x != nil {
		return x.RecordsFiltered
	}
	return 0
}

func (x *LegacyProductsResponse) GetData() []*LegacyProductRow {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCodesRequest) Reset() {
	*x = BatchCodesRequest{}
	mi := &file_kompetitor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCodesRequest) ProtoMessage() {}

func (x *BatchCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCodesRequest.ProtoReflect.Descriptor instead.
func (*BatchCodesRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{24}
}

type BatchCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCodesResponse) Reset() {
	*x = BatchCodesResponse{}
	mi := &file_kompetitor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCodesResponse) ProtoMessage() {}

func (x *BatchCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCodesResponse.ProtoReflect.Descriptor instead.
func (*BatchCodesResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{25}
}

func (x *BatchCodesResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type FilterOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOptionsRequest) Reset() {
	*x = FilterOptionsRequest{}
	mi := &file_kompetitor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOptionsRequest) ProtoMessage() {}

func (x *FilterOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOptionsRequest.ProtoReflect.Descriptor instead.
func (*FilterOptionsRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{26}
}

type FilterOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []string               `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	Kategoris     []string               `protobuf:"bytes,2,rep,name=kategoris,proto3" json:"kategoris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOptionsResponse) Reset() {
	*x = FilterOptionsResponse{}
	mi := &file_kompetitor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOptionsResponse) ProtoMessage() {}

func (x *FilterOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOptionsResponse.ProtoReflect.Descriptor instead.
func (*FilterOptionsResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{27}
}

func (x *FilterOptionsResponse) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *FilterOptionsResponse) GetKategoris() []string {
	if x != nil {
		return x.Kategoris
	}
	return nil
}

type OurProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Brand         []string               `protobuf:"bytes,2,rep,name=brand,proto3" json:"brand,omitempty"`
	Kategori      []string               `protobuf:"bytes,3,rep,name=kategori,proto3" json:"kategori,omitempty"`
	Abc           []string               `protobuf:"bytes,4,rep,name=abc,proto3" json:"abc,omitempty"`
	Start         int32                  `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Length        int32                  `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	Draw          int32                  `protobuf:"varint,7,opt,name=draw,proto3" json:"draw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OurProductsRequest) Reset() {
	*x = OurProductsRequest{}
	mi := &file_kompetitor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OurProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OurProductsRequest) ProtoMessage() {}

func (x *OurProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OurProductsRequest.ProtoReflect.Descriptor instead.
func (*OurProductsRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{28}
}

func (x *OurProductsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *OurProductsRequest) GetBrand() []string {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *OurProductsRequest) GetKategori() []string {
	if x != nil {
		return x.Kategori
	}
	return nil
}

func (x *OurProductsRequest) GetAbc() []string {
	if x != nil {
		return x.Abc
	}
	return nil
}

func (x *OurProductsRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *OurProductsRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *OurProductsRequest) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

// KompetitorCell is one kompetitor column: store name + matched product
// price + the batch date that price came from. stale = the price comes from
// an older batch because the store was not scraped in the latest one;
// belum_scrape marks a store absent from the latest batch, so an empty cell
// can be told apart from "checked, nothing found".
type KompetitorCell struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kompetitor      string                 `protobuf:"bytes,1,opt,name=kompetitor,proto3" json:"kompetitor,omitempty"`
	NamaProduk      *string                `protobuf:"bytes,2,opt,name=nama_produk,json=namaProduk,proto3,oneof" json:"nama_produk,omitempty"`
	Harga           *float64               `protobuf:"fixed64,3,opt,name=harga,proto3,oneof" json:"harga,omitempty"`
	TanggalScraping *string                `protobuf:"bytes,4,opt,name=tanggal_scraping,json=tanggalScraping,proto3,oneof" json:"tanggal_scraping,omitempty"`
	Stale           bool                   `protobuf:"varint,5,opt,name=stale,proto3" json:"stale,omitempty"`
	BelumScrape     bool                   `protobuf:"varint,6,opt,name=belum_scrape,json=belumScrape,proto3" json:"belum_scrape,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KompetitorCell) Reset() {
	*x = KompetitorCell{}
	mi := &file_kompetitor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KompetitorCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KompetitorCell) ProtoMessage() {}

func (x *KompetitorCell) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KompetitorCell.ProtoReflect.Descriptor instead.
func (*KompetitorCell) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{29}
}

func (x *KompetitorCell) GetKompetitor() string {
	if x != nil {
		return x.Kompetitor
	}
	return ""
}

func (x *KompetitorCell) GetNamaProduk() string {
	if x != nil && x.NamaProduk != nil {
		return *x.NamaProduk
	}
	return ""
}

func (x *KompetitorCell) GetHarga() float64 {
	if x != nil && x.Harga != nil {
		return *x.Harga
	}
	return 0
}

func (x *KompetitorCell) GetTanggalScraping() string {
	if x != nil && x.TanggalScraping != nil {
		return *x.TanggalScraping
	}
	return ""
}

func (x *KompetitorCell) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *KompetitorCell) GetBelumScrape() bool {
	if x != nil {
		return x.BelumScrape
	}
	return false
}

type OurProductRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku             string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Nama            string                 `protobuf:"bytes,3,opt,name=nama,proto3" json:"nama,omitempty"`
	Kategori        string                 `protobuf:"bytes,4,opt,name=kategori,proto3" json:"kategori,omitempty"`
	Brand           string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	HppLatest       float64                `protobuf:"fixed64,6,opt,name=hpp_latest,json=hppLatest,proto3" json:"hpp_latest,omitempty"`
	HargaShopee     float64                `protobuf:"fixed64,7,opt,name=harga_shopee,json=hargaShopee,proto3" json:"harga_shopee,omitempty"`
	HargaTayang     *KompetitorCell        `protobuf:"bytes,8,opt,name=harga_tayang,json=hargaTayang,proto3" json:"harga_tayang,omitempty"`
	MarginShopee    *float64               `protobuf:"fixed64,9,opt,name=margin_shopee,json=marginShopee,proto3,oneof" json:"margin_shopee,omitempty"`
	Abc             *string                `protobuf:"bytes,10,opt,name=abc,proto3,oneof" json:"abc,omitempty"`
	KompetitorHarga []*KompetitorCell      `protobuf:"bytes,11,rep,name=kompetitor_harga,json=kompetitorHarga,proto3" json:"kompetitor_harga,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OurProductRow) Reset() {
	*x = OurProductRow{}
	mi := &file_kompetitor_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OurProductRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OurProductRow) ProtoMessage() {}

func (x *OurProductRow) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OurProductRow.ProtoReflect.Descriptor instead.
func (*OurProductRow) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{30}
}

func (x *OurProductRow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OurProductRow) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OurProductRow) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *OurProductRow) GetKategori() string {
	if x != nil {
		return x.Kategori
	}
	return ""
}

func (x *OurProductRow) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *OurProductRow) GetHppLatest() float64 {
	if x != nil {
		return x.HppLatest
	}
	return 0
}

func (x *OurProductRow) GetHargaShopee() float64 {
	if x != nil {
		return x.HargaShopee
	}
	return 0
}

func (x *OurProductRow) GetHargaTayang() *KompetitorCell {
	if x != nil {
		return x.HargaTayang
	}
	return nil
}

func (x *OurProductRow) GetMarginShopee() float64 {
	if x != nil && x.MarginShopee != nil {
		return *x.MarginShopee
	}
	return 0
}

func (x *OurProductRow) GetAbc() string {
	if x != nil && x.Abc != nil {
		return *x.Abc
	}
	return ""
}

func (x *OurProductRow) GetKompetitorHarga() []*KompetitorCell {
	if x != nil {
		return x.KompetitorHarga
	}
	return nil
}

type OurProductsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Draw            int32                  `protobuf:"varint,1,opt,name=draw,proto3" json:"draw,omitempty"`
	RecordsTotal    int64                  `protobuf:"varint,2,opt,name=records_total,json=recordsTotal,proto3" json:"records_total,omitempty"`
	RecordsFiltered int64                  `protobuf:"varint,3,opt,name=records_filtered,json=recordsFiltered,proto3" json:"records_filtered,omitempty"`
	Data            []*OurProductRow       `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OurProductsResponse) Reset() {
	*x = OurProductsResponse{}
	mi := &file_kompetitor_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OurProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OurProductsResponse) ProtoMessage() {}

func (x *OurProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OurProductsResponse.ProtoReflect.Descriptor instead.
func (*OurProductsResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{31}
}

func (x *OurProductsResponse) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

func (x *OurProductsResponse) GetRecordsTotal() int64 {
	if x != nil {
		return x.RecordsTotal
	}
	return 0
}

func (x *OurProductsResponse) GetRecordsFiltered() int64 {
	if x != nil {
		return x.RecordsFiltered
	}
	return 0
}

func (x *OurProductsResponse) GetData() []*OurProductRow {
	if x != nil {
		return x.Data
	}
	return nil
}

type IngestProduct struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price          float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	SoldMonthly    int64                  `protobuf:"varint,3,opt,name=sold_monthly,json=soldMonthly,proto3" json:"sold_monthly,omitempty"`
	RevenueMonthly float64                `protobuf:"fixed64,4,opt,name=revenue_monthly,json=revenueMonthly,proto3" json:"revenue_monthly,omitempty"`
	SoldWeekly     int64                  `protobuf:"varint,5,opt,name=sold_weekly,json=soldWeekly,proto3" json:"sold_weekly,omitempty"`
	RevenueWeekly  float64                `protobuf:"fixed64,6,opt,name=revenue_weekly,json=revenueWeekly,proto3" json:"revenue_weekly,omitempty"`
	Rating         *float64               `protobuf:"fixed64,7,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	WishlistCount  int64                  `protobuf:"varint,8,opt,name=wishlist_count,json=wishlistCount,proto3" json:"wishlist_count,omitempty"`
	Stock          int64                  `protobuf:"varint,9,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestProduct) Reset() {
	*x = IngestProduct{}
	mi := &file_kompetitor_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestProduct) ProtoMessage() {}

func (x *IngestProduct) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestProduct.ProtoReflect.Descriptor instead.
func (*IngestProduct) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{32}
}

func (x *IngestProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngestProduct) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *IngestProduct) GetSoldMonthly() int64 {
	if x != nil {
		return x.SoldMonthly
	}
	return 0
}

func (x *IngestProduct) GetRevenueMonthly() float64 {
	if x != nil {
		return x.RevenueMonthly
	}
	return 0
}

func (x *IngestProduct) GetSoldWeekly() int64 {
	if x != nil {
		return x.SoldWeekly
	}
	return 0
}

func (x *IngestProduct) GetRevenueWeekly() float64 {
	if x != nil {
		return x.RevenueWeekly
	}
	return 0
}

func (x *IngestProduct) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *IngestProduct) GetWishlistCount() int64 {
	if x != nil {
		return x.WishlistCount
	}
	return 0
}

func (x *IngestProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ImportProductsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	KompetitorId uint64                 `protobuf:"varint,1,opt,name=kompetitor_id,json=kompetitorId,proto3" json:"kompetitor_id,omitempty"`
	// executed_at is YYYY-MM-DD; batch_code empty = "import-<Ymd>".
	ExecutedAt    string           `protobuf:"bytes,2,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	BatchCode     string           `protobuf:"bytes,3,opt,name=batch_code,json=batchCode,proto3" json:"batch_code,omitempty"`
	Products      []*IngestProduct `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProductsRequest) Reset() {
	*x = ImportProductsRequest{}
	mi := &file_kompetitor_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProductsRequest) ProtoMessage() {}

func (x *ImportProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProductsRequest.ProtoReflect.Descriptor instead.
func (*ImportProductsRequest) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{33}
}

func (x *ImportProductsRequest) GetKompetitorId() uint64 {
	if x != nil {
		return x.KompetitorId
	}
	return 0
}

func (x *ImportProductsRequest) GetExecutedAt() string {
	if x != nil {
		return x.ExecutedAt
	}
	return ""
}

func (x *ImportProductsRequest) GetBatchCode() string {
	if x != nil {
		return x.BatchCode
	}
	return ""
}

func (x *ImportProductsRequest) GetProducts() []*IngestProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type ImportProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchCode     string                 `protobuf:"bytes,1,opt,name=batch_code,json=batchCode,proto3" json:"batch_code,omitempty"`
	ExecutedAt    string                 `protobuf:"bytes,2,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	TotalProducts int32                  `protobuf:"varint,3,opt,name=total_products,json=totalProducts,proto3" json:"total_products,omitempty"`
	Kompetitor    string                 `protobuf:"bytes,4,opt,name=kompetitor,proto3" json:"kompetitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProductsResponse) Reset() {
	*x = ImportProductsResponse{}
	mi := &file_kompetitor_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProductsResponse) ProtoMessage() {}

func (x *ImportProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kompetitor_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProductsResponse.ProtoReflect.Descriptor instead.
func (*ImportProductsResponse) Descriptor() ([]byte, []int) {
	return file_kompetitor_proto_rawDescGZIP(), []int{34}
}

func (x *ImportProductsResponse) GetBatchCode() string {
	if x != nil {
		return x.BatchCode
	}
	return ""
}

func (x *ImportProductsResponse) GetExecutedAt() string {
	if x != nil {
		return x.ExecutedAt
	}
	return ""
}

func (x *ImportProductsResponse) GetTotalProducts() int32 {
	if x != nil {
		return x.TotalProducts
	}
	return 0
}

func (x *ImportProductsResponse) GetKompetitor() string {
	if x != nil {
		return x.Kompetitor
	}
	return ""
}

var File_kompetitor_proto protoreflect.FileDescriptor

const file_kompetitor_proto_rawDesc = "" +
	"\n" +
	"\x10kompetitor.proto\x12\n" +
	"kompetitor\".\n" +
	"\bNamedRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10IndexMetaRequest\"X\n" +
	"\x11KompetitorMetaRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmust_scrape\x18\x03 \x01(\bR\n" +
	"mustScrape\"\xc3\x02\n" +
	"\x11IndexMetaResponse\x12=\n" +
	"\x0flist_kompetitor\x18\x01 \x03(\v2\x14.kompetitor.NamedRowR\x0elistKompetitor\x12M\n" +
	"\x13list_all_kompetitor\x18\x02 \x03(\v2\x1d.kompetitor.KompetitorMetaRowR\x11listAllKompetitor\x120\n" +
	"\x14dbklik_kompetitor_id\x18\x03 \x01(\x04R\x12dbklikKompetitorId\x123\n" +
	"\n" +
	"list_brand\x18\x04 \x03(\v2\x14.kompetitor.NamedRowR\tlistBrand\x129\n" +
	"\rlist_kategori\x18\x05 \x03(\v2\x14.kompetitor.NamedRowR\flistKategori\"\x13\n" +
	"\x11ManageDataRequest\"\xc1\x01\n" +
	"\rKompetitorRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vshopee_code\x18\x03 \x01(\tR\n" +
	"shopeeCode\x12%\n" +
	"\x0etokopedia_code\x18\x04 \x01(\tR\rtokopediaCode\x12\x1f\n" +
	"\vmust_scrape\x18\x05 \x01(\bR\n" +
	"mustScrape\x12#\n" +
	"\rmapping_count\x18\x06 \x01(\x03R\fmappingCount\"C\n" +
	"\x12ManageDataResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.kompetitor.KompetitorRowR\x04data\"\xa4\x01\n" +
	"\x15SaveKompetitorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vshopee_code\x18\x03 \x01(\tR\n" +
	"shopeeCode\x12%\n" +
	"\x0etokopedia_code\x18\x04 \x01(\tR\rtokopediaCode\x12\x1f\n" +
	"\vmust_scrape\x18\x05 \x01(\bR\n" +
	"mustScrape\")\n" +
	"\x17DeleteKompetitorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"L\n" +
	"\x14MappingMatrixRequest\x12\x16\n" +
	"\x06brands\x18\x01 \x03(\x04R\x06brands\x12\x1c\n" +
	"\tkategoris\x18\x02 \x03(\x04R\tkategoris\"\xbe\x03\n" +
	"\x15MappingMatrixResponse\x12,\n" +
	"\x06brands\x18\x01 \x03(\v2\x14.kompetitor.NamedRowR\x06brands\x122\n" +
	"\tkategoris\x18\x02 \x03(\v2\x14.kompetitor.NamedRowR\tkategoris\x12E\n" +
	"\x06counts\x18\x03 \x03(\v2-.kompetitor.MappingMatrixResponse.CountsEntryR\x06counts\x12a\n" +
	"\x10universal_counts\x18\x04 \x03(\v26.kompetitor.MappingMatrixResponse.UniversalCountsEntryR\x0funiversalCounts\x12\x1a\n" +
	"\bfiltered\x18\x05 \x01(\bR\bfiltered\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14UniversalCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"e\n" +
	"\x12MappingCellRequest\x12$\n" +
	"\vkategori_id\x18\x01 \x01(\x04H\x00R\n" +
	"kategoriId\x88\x01\x01\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\x04R\abrandIdB\x0e\n" +
	"\f_kategori_id\"<\n" +
	"\x13MappingCellResponse\x12%\n" +
	"\x0ekompetitor_ids\x18\x01 \x03(\x04R\rkompetitorIds\"\x8d\x01\n" +
	"\x18MappingCellUpdateRequest\x12$\n" +
	"\vkategori_id\x18\x01 \x01(\x04H\x00R\n" +
	"kategoriId\x88\x01\x01\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\x04R\abrandId\x12 \n" +
	"\vkompetitors\x18\x03 \x03(\x04R\vkompetitorsB\x0e\n" +
	"\f_kategori_id\"m\n" +
	"\fStatsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12#\n" +
	"\rkompetitor_id\x18\x03 \x01(\x04R\fkompetitorId\"\xe9\x02\n" +
	"\fStatsMetrics\x12\x1f\n" +
	"\vtotal_omzet\x18\x01 \x01(\x01R\n" +
	"totalOmzet\x12*\n" +
	"\x11rata_omzet_minggu\x18\x02 \x01(\x01R\x0frataOmzetMinggu\x12&\n" +
	"\x0frata_omzet_hari\x18\x03 \x01(\x01R\rrataOmzetHari\x12#\n" +
	"\rtotal_terjual\x18\x04 \x01(\x03R\ftotalTerjual\x12.\n" +
	"\x13rata_terjual_minggu\x18\x05 \x01(\x01R\x11rataTerjualMinggu\x12*\n" +
	"\x11rata_terjual_hari\x18\x06 \x01(\x01R\x0frataTerjualHari\x12\x1d\n" +
	"\n" +
	"rata_harga\x18\a \x01(\x03R\trataHarga\x12!\n" +
	"\fproduk_ready\x18\b \x01(\x03R\vprodukReady\x12!\n" +
	"\fproduk_habis\x18\t \x01(\x03R\vprodukHabis\"\xcd\x01\n" +
	"\rStatsResponse\x122\n" +
	"\acurrent\x18\x01 \x01(\v2\x18.kompetitor.StatsMetricsR\acurrent\x124\n" +
	"\bprevious\x18\x02 \x01(\v2\x18.kompetitor.StatsMetricsR\bprevious\x12'\n" +
	"\x0fcurrent_batches\x18\x03 \x03(\x04R\x0ecurrentBatches\x12)\n" +
	"\x10previous_batches\x18\x04 \x03(\x04R\x0fpreviousBatches\"\xca\x01\n" +
	"\x0fProductsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12#\n" +
	"\rkompetitor_id\x18\x03 \x01(\x04R\fkompetitorId\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x14\n" +
	"\x05start\x18\x05 \x01(\x05R\x05start\x12\x16\n" +
	"\x06length\x18\x06 \x01(\x05R\x06length\x12\x12\n" +
	"\x04draw\x18\a \x01(\x05R\x04draw\"\xf3\x02\n" +
	"\n" +
	"ProductRow\x12\x1e\n" +
	"\n" +
	"kompetitor\x18\x01 \x01(\tR\n" +
	"kompetitor\x12\x1f\n" +
	"\vnama_produk\x18\x02 \x01(\tR\n" +
	"namaProduk\x12\x14\n" +
	"\x05harga\x18\x03 \x01(\tR\x05harga\x12,\n" +
	"\x0fperubahan_harga\x18\x04 \x01(\x01H\x00R\x0eperubahanHarga\x88\x01\x01\x12*\n" +
	"\x11terjual_per_bulan\x18\x05 \x01(\x03R\x0fterjualPerBulan\x12\x1e\n" +
	"\n" +
	"pendapatan\x18\x06 \x01(\tR\n" +
	"pendapatan\x12\x1b\n" +
	"\trata_hari\x18\a \x01(\tR\brataHari\x12\x1b\n" +
	"\x06rating\x18\b \x01(\x01H\x01R\x06rating\x88\x01\x01\x12\x17\n" +
	"\x04stok\x18\t \x01(\x03H\x02R\x04stok\x88\x01\x01\x12\x19\n" +
	"\bbatch_id\x18\n" +
	" \x01(\tR\abatchIdB\x12\n" +
	"\x10_perubahan_hargaB\t\n" +
	"\a_ratingB\a\n" +
	"\x05_stok\"\xa2\x01\n" +
	"\x10ProductsResponse\x12\x12\n" +
	"\x04draw\x18\x01 \x01(\x05R\x04draw\x12#\n" +
	"\rrecords_total\x18\x02 \x01(\x03R\frecordsTotal\x12)\n" +
	"\x10records_filtered\x18\x03 \x01(\x03R\x0frecordsFiltered\x12*\n" +
	"\x04data\x18\x04 \x03(\v2\x16.kompetitor.ProductRowR\x04data\"\xa7\x01\n" +
	"\x15LegacyProductsRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x1e\n" +
	"\n" +
	"kompetitor\x18\x02 \x01(\tR\n" +
	"kompetitor\x12\x14\n" +
	"\x05batch\x18\x03 \x01(\tR\x05batch\x12\x14\n" +
	"\x05start\x18\x04 \x01(\x05R\x05start\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x05R\x06length\x12\x12\n" +
	"\x04draw\x18\x06 \x01(\x05R\x04draw\"\xb2\x02\n" +
	"\x10LegacyProductRow\x12\x1e\n" +
	"\n" +
	"kompetitor\x18\x01 \x01(\tR\n" +
	"kompetitor\x12\x1f\n" +
	"\vnama_produk\x18\x02 \x01(\tR\n" +
	"namaProduk\x12\x14\n" +
	"\x05harga\x18\x03 \x01(\tR\x05harga\x12\x1b\n" +
	"\tharga_raw\x18\x04 \x01(\x01R\bhargaRaw\x12*\n" +
	"\x11terjual_per_bulan\x18\x05 \x01(\x03R\x0fterjualPerBulan\x12\x1e\n" +
	"\n" +
	"pendapatan\x18\x06 \x01(\tR\n" +
	"pendapatan\x12\x1b\n" +
	"\trata_hari\x18\a \x01(\tR\brataHari\x12\x1b\n" +
	"\x06rating\x18\b \x01(\x01H\x00R\x06rating\x88\x01\x01\x12\x19\n" +
	"\bbatch_id\x18\t \x01(\tR\abatchIdB\t\n" +
	"\a_rating\"\xae\x01\n" +
	"\x16LegacyProductsResponse\x12\x12\n" +
	"\x04draw\x18\x01 \x01(\x05R\x04draw\x12#\n" +
	"\rrecords_total\x18\x02 \x01(\x03R\frecordsTotal\x12)\n" +
	"\x10records_filtered\x18\x03 \x01(\x03R\x0frecordsFiltered\x120\n" +
	"\x04data\x18\x04 \x03(\v2\x1c.kompetitor.LegacyProductRowR\x04data\"\x13\n" +
	"\x11BatchCodesRequest\"*\n" +
	"\x12BatchCodesResponse\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\x16\n" +
	"\x14FilterOptionsRequest\"M\n" +
	"\x15FilterOptionsResponse\x12\x16\n" +
	"\x06brands\x18\x01 \x03(\tR\x06brands\x12\x1c\n" +
	"\tkategoris\x18\x02 \x03(\tR\tkategoris\"\xb2\x01\n" +
	"\x12OurProductsRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x14\n" +
	"\x05brand\x18\x02 \x03(\tR\x05brand\x12\x1a\n" +
	"\bkategori\x18\x03 \x03(\tR\bkategori\x12\x10\n" +
	"\x03abc\x18\x04 \x03(\tR\x03abc\x12\x14\n" +
	"\x05start\x18\x05 \x01(\x05R\x05start\x12\x16\n" +
	"\x06length\x18\x06 \x01(\x05R\x06length\x12\x12\n" +
	"\x04draw\x18\a \x01(\x05R\x04draw\"\x89\x02\n" +
	"\x0eKompetitorCell\x12\x1e\n" +
	"\n" +
	"kompetitor\x18\x01 \x01(\tR\n" +
	"kompetitor\x12$\n" +
	"\vnama_produk\x18\x02 \x01(\tH\x00R\n" +
	"namaProduk\x88\x01\x01\x12\x19\n" +
	"\x05harga\x18\x03 \x01(\x01H\x01R\x05harga\x88\x01\x01\x12.\n" +
	"\x10tanggal_scraping\x18\x04 \x01(\tH\x02R\x0ftanggalScraping\x88\x01\x01\x12\x14\n" +
	"\x05stale\x18\x05 \x01(\bR\x05stale\x12!\n" +
	"\fbelum_scrape\x18\x06 \x01(\bR\vbelumScrapeB\x0e\n" +
	"\f_nama_produkB\b\n" +
	"\x06_hargaB\x13\n" +
	"\x11_tanggal_scraping\"\x9a\x03\n" +
	"\rOurProductRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04nama\x18\x03 \x01(\tR\x04nama\x12\x1a\n" +
	"\bkategori\x18\x04 \x01(\tR\bkategori\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x1d\n" +
	"\n" +
	"hpp_latest\x18\x06 \x01(\x01R\thppLatest\x12!\n" +
	"\fharga_shopee\x18\a \x01(\x01R\vhargaShopee\x12=\n" +
	"\fharga_tayang\x18\b \x01(\v2\x1a.kompetitor.KompetitorCellR\vhargaTayang\x12(\n" +
	"\rmargin_shopee\x18\t \x01(\x01H\x00R\fmarginShopee\x88\x01\x01\x12\x15\n" +
	"\x03abc\x18\n" +
	" \x01(\tH\x01R\x03abc\x88\x01\x01\x12E\n" +
	"\x10kompetitor_harga\x18\v \x03(\v2\x1a.kompetitor.KompetitorCellR\x0fkompetitorHargaB\x10\n" +
	"\x0e_margin_shopeeB\x06\n" +
	"\x04_abc\"\xa8\x01\n" +
	"\x13OurProductsResponse\x12\x12\n" +
	"\x04draw\x18\x01 \x01(\x05R\x04draw\x12#\n" +
	"\rrecords_total\x18\x02 \x01(\x03R\frecordsTotal\x12)\n" +
	"\x10records_filtered\x18\x03 \x01(\x03R\x0frecordsFiltered\x12-\n" +
	"\x04data\x18\x04 \x03(\v2\x19.kompetitor.OurProductRowR\x04data\"\xb2\x02\n" +
	"\rIngestProduct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12!\n" +
	"\fsold_monthly\x18\x03 \x01(\x03R\vsoldMonthly\x12'\n" +
	"\x0frevenue_monthly\x18\x04 \x01(\x01R\x0erevenueMonthly\x12\x1f\n" +
	"\vsold_weekly\x18\x05 \x01(\x03R\n" +
	"soldWeekly\x12%\n" +
	"\x0erevenue_weekly\x18\x06 \x01(\x01R\rrevenueWeekly\x12\x1b\n" +
	"\x06rating\x18\a \x01(\x01H\x00R\x06rating\x88\x01\x01\x12%\n" +
	"\x0ewishlist_count\x18\b \x01(\x03R\rwishlistCount\x12\x14\n" +
	"\x05stock\x18\t \x01(\x03R\x05stockB\t\n" +
	"\a_rating\"\xb3\x01\n" +
	"\x15ImportProductsRequest\x12#\n" +
	"\rkompetitor_id\x18\x01 \x01(\x04R\fkompetitorId\x12\x1f\n" +
	"\vexecuted_at\x18\x02 \x01(\tR\n" +
	"executedAt\x12\x1d\n" +
	"\n" +
	"batch_code\x18\x03 \x01(\tR\tbatchCode\x125\n" +
	"\bproducts\x18\x04 \x03(\v2\x19.kompetitor.IngestProductR\bproducts\"\x9f\x01\n" +
	"\x16ImportProductsResponse\x12\x1d\n" +
	"\n" +
	"batch_code\x18\x01 \x01(\tR\tbatchCode\x12\x1f\n" +
	"\vexecuted_at\x18\x02 \x01(\tR\n" +
	"executedAt\x12%\n" +
	"\x0etotal_products\x18\x03 \x01(\x05R\rtotalProducts\x12\x1e\n" +
	"\n" +
	"kompetitor\x18\x04 \x01(\tR\n" +
	"kompetitor2\xd0\t\n" +
	"\x11KompetitorService\x12H\n" +
	"\tIndexMeta\x12\x1c.kompetitor.IndexMetaRequest\x1a\x1d.kompetitor.IndexMetaResponse\x12K\n" +
	"\n" +
	"ManageData\x12\x1d.kompetitor.ManageDataRequest\x1a\x1e.kompetitor.ManageDataResponse\x12R\n" +
	"\x10CreateKompetitor\x12!.kompetitor.SaveKompetitorRequest\x1a\x1b.kompetitor.MessageResponse\x12R\n" +
	"\x10UpdateKompetitor\x12!.kompetitor.SaveKompetitorRequest\x1a\x1b.kompetitor.MessageResponse\x12T\n" +
	"\x10DeleteKompetitor\x12#.kompetitor.DeleteKompetitorRequest\x1a\x1b.kompetitor.MessageResponse\x12T\n" +
	"\rMappingMatrix\x12 .kompetitor.MappingMatrixRequest\x1a!.kompetitor.MappingMatrixResponse\x12N\n" +
	"\vMappingCell\x12\x1e.kompetitor.MappingCellRequest\x1a\x1f.kompetitor.MappingCellResponse\x12V\n" +
	"\x11MappingCellUpdate\x12$.kompetitor.MappingCellUpdateRequest\x1a\x1b.kompetitor.MessageResponse\x12<\n" +
	"\x05Stats\x12\x18.kompetitor.StatsRequest\x1a\x19.kompetitor.StatsResponse\x12E\n" +
	"\bProducts\x12\x1b.kompetitor.ProductsRequest\x1a\x1c.kompetitor.ProductsResponse\x12W\n" +
	"\x0eLegacyProducts\x12!.kompetitor.LegacyProductsRequest\x1a\".kompetitor.LegacyProductsResponse\x12K\n" +
	"\n" +
	"BatchCodes\x12\x1d.kompetitor.BatchCodesRequest\x1a\x1e.kompetitor.BatchCodesResponse\x12T\n" +
	"\rFilterOptions\x12 .kompetitor.FilterOptionsRequest\x1a!.kompetitor.FilterOptionsResponse\x12N\n" +
	"\vOurProducts\x12\x1e.kompetitor.OurProductsRequest\x1a\x1f.kompetitor.OurProductsResponse\x12W\n" +
	"\x0eImportProducts\x12!.kompetitor.ImportProductsRequest\x1a\".kompetitor.ImportProductsResponseBXZVgithub.com/dbklik/dbklik-kompetitor-service/modules/kompetitor/presentation/grpc/pb;pbb\x06proto3"

var (
	file_kompetitor_proto_rawDescOnce sync.Once
	file_kompetitor_proto_rawDescData []byte
)

func file_kompetitor_proto_rawDescGZIP() []byte {
	file_kompetitor_proto_rawDescOnce.Do(func() {
		file_kompetitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kompetitor_proto_rawDesc), len(file_kompetitor_proto_rawDesc)))
	})
	return file_kompetitor_proto_rawDescData
}

var file_kompetitor_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_kompetitor_proto_goTypes = []any{
	(*NamedRow)(nil),                 // 0: kompetitor.NamedRow
	(*MessageResponse)(nil),          // 1: kompetitor.MessageResponse
	(*IndexMetaRequest)(nil),         // 2: kompetitor.IndexMetaRequest
	(*KompetitorMetaRow)(nil),        // 3: kompetitor.KompetitorMetaRow
	(*IndexMetaResponse)(nil),        // 4: kompetitor.IndexMetaResponse
	(*ManageDataRequest)(nil),        // 5: kompetitor.ManageDataRequest
	(*KompetitorRow)(nil),            // 6: kompetitor.KompetitorRow
	(*ManageDataResponse)(nil),       // 7: kompetitor.ManageDataResponse
	(*SaveKompetitorRequest)(nil),    // 8: kompetitor.SaveKompetitorRequest
	(*DeleteKompetitorRequest)(nil),  // 9: kompetitor.DeleteKompetitorRequest
	(*MappingMatrixRequest)(nil),     // 10: kompetitor.MappingMatrixRequest
	(*MappingMatrixResponse)(nil),    // 11: kompetitor.MappingMatrixResponse
	(*MappingCellRequest)(nil),       // 12: kompetitor.MappingCellRequest
	(*MappingCellResponse)(nil),      // 13: kompetitor.MappingCellResponse
	(*MappingCellUpdateRequest)(nil), // 14: kompetitor.MappingCellUpdateRequest
	(*StatsRequest)(nil),             // 15: kompetitor.StatsRequest
	(*StatsMetrics)(nil),             // 16: kompetitor.StatsMetrics
	(*StatsResponse)(nil),            // 17: kompetitor.StatsResponse
	(*ProductsRequest)(nil),          // 18: kompetitor.ProductsRequest
	(*ProductRow)(nil),               // 19: kompetitor.ProductRow
	(*ProductsResponse)(nil),         // 20: kompetitor.ProductsResponse
	(*LegacyProductsRequest)(nil),    // 21: kompetitor.LegacyProductsRequest
	(*LegacyProductRow)(nil),         // 22: kompetitor.LegacyProductRow
	(*LegacyProductsResponse)(nil),   // 23: kompetitor.LegacyProductsResponse
	(*BatchCodesRequest)(nil),        // 24: kompetitor.BatchCodesRequest
	(*BatchCodesResponse)(nil),       // 25: kompetitor.BatchCodesResponse
	(*FilterOptionsRequest)(nil),     // 26: kompetitor.FilterOptionsRequest
	(*FilterOptionsResponse)(nil),    // 27: kompetitor.FilterOptionsResponse
	(*OurProductsRequest)(nil),       // 28: kompetitor.OurProductsRequest
	(*KompetitorCell)(nil),           // 29: kompetitor.KompetitorCell
	(*OurProductRow)(nil),            // 30: kompetitor.OurProductRow
	(*OurProductsResponse)(nil),      // 31: kompetitor.OurProductsResponse
	(*IngestProduct)(nil),            // 32: kompetitor.IngestProduct
	(*ImportProductsRequest)(nil),    // 33: kompetitor.ImportProductsRequest
	(*ImportProductsResponse)(nil),   // 34: kompetitor.ImportProductsResponse
	nil,                              // 35: kompetitor.MappingMatrixResponse.CountsEntry
	nil,                              // 36: kompetitor.MappingMatrixResponse.UniversalCountsEntry
}
var file_kompetitor_proto_depIdxs = []int32{
	0,  // 0: kompetitor.IndexMetaResponse.list_kompetitor:type_name -> kompetitor.NamedRow
	3,  // 1: kompetitor.IndexMetaResponse.list_all_kompetitor:type_name -> kompetitor.KompetitorMetaRow
	0,  // 2: kompetitor.IndexMetaResponse.list_brand:type_name -> kompetitor.NamedRow
	0,  // 3: kompetitor.IndexMetaResponse.list_kategori:type_name -> kompetitor.NamedRow
	6,  // 4: kompetitor.ManageDataResponse.data:type_name -> kompetitor.KompetitorRow
	0,  // 5: kompetitor.MappingMatrixResponse.brands:type_name -> kompetitor.NamedRow
	0,  // 6: kompetitor.MappingMatrixResponse.kategoris:type_name -> kompetitor.NamedRow
	35, // 7: kompetitor.MappingMatrixResponse.counts:type_name -> kompetitor.MappingMatrixResponse.CountsEntry
	36, // 8: kompetitor.MappingMatrixResponse.universal_counts:type_name -> kompetitor.MappingMatrixResponse.UniversalCountsEntry
	16, // 9: kompetitor.StatsResponse.current:type_name -> kompetitor.StatsMetrics
	16, // 10: kompetitor.StatsResponse.previous:type_name -> kompetitor.StatsMetrics
	19, // 11: kompetitor.ProductsResponse.data:type_name -> kompetitor.ProductRow
	22, // 12: kompetitor.LegacyProductsResponse.data:type_name -> kompetitor.LegacyProductRow
	29, // 13: kompetitor.OurProductRow.harga_tayang:type_name -> kompetitor.KompetitorCell
	29, // 14: kompetitor.OurProductRow.kompetitor_harga:type_name -> kompetitor.KompetitorCell
	30, // 15: kompetitor.OurProductsResponse.data:type_name -> kompetitor.OurProductRow
	32, // 16: kompetitor.ImportProductsRequest.products:type_name -> kompetitor.IngestProduct
	2,  // 17: kompetitor.KompetitorService.IndexMeta:input_type -> kompetitor.IndexMetaRequest
	5,  // 18: kompetitor.KompetitorService.ManageData:input_type -> kompetitor.ManageDataRequest
	8,  // 19: kompetitor.KompetitorService.CreateKompetitor:input_type -> kompetitor.SaveKompetitorRequest
	8,  // 20: kompetitor.KompetitorService.UpdateKompetitor:input_type -> kompetitor.SaveKompetitorRequest
	9,  // 21: kompetitor.KompetitorService.DeleteKompetitor:input_type -> kompetitor.DeleteKompetitorRequest
	10, // 22: kompetitor.KompetitorService.MappingMatrix:input_type -> kompetitor.MappingMatrixRequest
	12, // 23: kompetitor.KompetitorService.MappingCell:input_type -> kompetitor.MappingCellRequest
	14, // 24: kompetitor.KompetitorService.MappingCellUpdate:input_type -> kompetitor.MappingCellUpdateRequest
	15, // 25: kompetitor.KompetitorService.Stats:input_type -> kompetitor.StatsRequest
	18, // 26: kompetitor.KompetitorService.Products:input_type -> kompetitor.ProductsRequest
	21, // 27: kompetitor.KompetitorService.LegacyProducts:input_type -> kompetitor.LegacyProductsRequest
	24, // 28: kompetitor.KompetitorService.BatchCodes:input_type -> kompetitor.BatchCodesRequest
	26, // 29: kompetitor.KompetitorService.FilterOptions:input_type -> kompetitor.FilterOptionsRequest
	28, // 30: kompetitor.KompetitorService.OurProducts:input_type -> kompetitor.OurProductsRequest
	33, // 31: kompetitor.KompetitorService.ImportProducts:input_type -> kompetitor.ImportProductsRequest
	4,  // 32: kompetitor.KompetitorService.IndexMeta:output_type -> kompetitor.IndexMetaResponse
	7,  // 33: kompetitor.KompetitorService.ManageData:output_type -> kompetitor.ManageDataResponse
	1,  // 34: kompetitor.KompetitorService.CreateKompetitor:output_type -> kompetitor.MessageResponse
	1,  // 35: kompetitor.KompetitorService.UpdateKompetitor:output_type -> kompetitor.MessageResponse
	1,  // 36: kompetitor.KompetitorService.DeleteKompetitor:output_type -> kompetitor.MessageResponse
	11, // 37: kompetitor.KompetitorService.MappingMatrix:output_type -> kompetitor.MappingMatrixResponse
	13, // 38: kompetitor.KompetitorService.MappingCell:output_type -> kompetitor.MappingCellResponse
	1,  // 39: kompetitor.KompetitorService.MappingCellUpdate:output_type -> kompetitor.MessageResponse
	17, // 40: kompetitor.KompetitorService.Stats:output_type -> kompetitor.StatsResponse
	20, // 41: kompetitor.KompetitorService.Products:output_type -> kompetitor.ProductsResponse
	23, // 42: kompetitor.KompetitorService.LegacyProducts:output_type -> kompetitor.LegacyProductsResponse
	25, // 43: kompetitor.KompetitorService.BatchCodes:output_type -> kompetitor.BatchCodesResponse
	27, // 44: kompetitor.KompetitorService.FilterOptions:output_type -> kompetitor.FilterOptionsResponse
	31, // 45: kompetitor.KompetitorService.OurProducts:output_type -> kompetitor.OurProductsResponse
	34, // 46: kompetitor.KompetitorService.ImportProducts:output_type -> kompetitor.ImportProductsResponse
	32, // [32:47] is the sub-list for method output_type
	17, // [17:32] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_kompetitor_proto_init() }
func file_kompetitor_proto_init() {
	if File_kompetitor_proto != nil {
		return
	}
	file_kompetitor_proto_msgTypes[12].OneofWrappers = []any{}
	file_kompetitor_proto_msgTypes[14].OneofWrappers = []any{}
	file_kompetitor_proto_msgTypes[19].OneofWrappers = []any{}
	file_kompetitor_proto_msgTypes[22].OneofWrappers = []any{}
	file_kompetitor_proto_msgTypes[29].OneofWrappers = []any{}
	file_kompetitor_proto_msgTypes[30].OneofWrappers = []any{}
	file_kompetitor_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kompetitor_proto_rawDesc), len(file_kompetitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kompetitor_proto_goTypes,
		DependencyIndexes: file_kompetitor_proto_depIdxs,
		MessageInfos:      file_kompetitor_proto_msgTypes,
	}.Build()
	File_kompetitor_proto = out.File
	file_kompetitor_proto_goTypes = nil
	file_kompetitor_proto_depIdxs = nil
}
